#!/usr/bin/env python3
import eva




M                   = eva.M
BREATHER            = eva.Chrono(timeout=eva.SECOND * 20)
CPU_HIGHEST_THREAD  = max(eva.CPU.get_cpus(possible=True))
EVENTS              = None
FAHRENHEIT          = False
FONTS               = None
GLYPHS              = None
GUIDES              = None
INTERVAL_SMOOTHED   = eva.SECOND
INTERVAL_SNAPSHOT   = eva.SECOND
LOCK                = M.threading.RLock()
MARGIN_PERCENTAGE   = 1
SIGWINCH_IDLE       = True
SNAPSHOT            = None
STRESS              = False
STRESS_CHRONO       = eva.Chrono()
TEMPERATURE_MAXIMUM = 999.0
TEMPERATURE_MINIMUM = 0.0
TERMINAL            = eva.Terminal()
TIMEOUT_SMOOTHED    = eva.SECOND * 10
VERSION             = '1.260819'
WINDOWS             = None
ZONES               = None




@M.functools.cache
def build_events():
    ret          = eva.N()
    ret.bye      = M.threading.Event()
    ret.screen   = M.threading.Event()
    ret.sigwinch = M.threading.Event()
    ret.stress   = M.threading.Event()

    return ret




@M.functools.cache
def build_fonts():
    fallback = '?'
    glyphs   = build_glyphs().heavy
    ret      = eva.N()

    medium      = {}
    medium[' '] = (f'{glyphs.none}{glyphs.none}{glyphs.none}',
                   f'{glyphs.none}{glyphs.none}{glyphs.none}',
                   f'{glyphs.none}{glyphs.none}{glyphs.none}')
    medium['%'] = (f'{glyphs.es}{glyphs.sw}{glyphs.s}',
                   f'{glyphs.es}{glyphs.ew}{glyphs.nw}',
                   f'{glyphs.n}{glyphs.ne}{glyphs.nw}')
    medium[','] = (f'{glyphs.none}{glyphs.none}{glyphs.none}',
                   f'{glyphs.none}{glyphs.none}{glyphs.none}',
                   f'{glyphs.none}{glyphs.nw}{glyphs.none}')
    medium['.'] = (f'{glyphs.none}{glyphs.none}{glyphs.none}',
                   f'{glyphs.none}{glyphs.none}{glyphs.none}',
                   f'{glyphs.none}{glyphs.n}{glyphs.none}')
    medium['0'] = (f'{glyphs.es}{glyphs.ew}{glyphs.sw}',
                   f'{glyphs.ns}{glyphs.ns}{glyphs.ns}',
                   f'{glyphs.ne}{glyphs.ew}{glyphs.nw}')
    medium['1'] = (f'{glyphs.e}{glyphs.sw}{glyphs.none}',
                   f'{glyphs.none}{glyphs.ns}{glyphs.none}',
                   f'{glyphs.e}{glyphs.new}{glyphs.w}')
    medium['2'] = (f'{glyphs.es}{glyphs.ew}{glyphs.sw}',
                   f'{glyphs.es}{glyphs.ew}{glyphs.nw}',
                   f'{glyphs.ne}{glyphs.ew}{glyphs.w}')
    medium['3'] = (f'{glyphs.es}{glyphs.ew}{glyphs.sw}',
                   f'{glyphs.e}{glyphs.ew}{glyphs.nsw}',
                   f'{glyphs.ne}{glyphs.ew}{glyphs.nw}')
    medium['4'] = (f'{glyphs.s}{glyphs.none}{glyphs.s}',
                   f'{glyphs.ne}{glyphs.ew}{glyphs.nsw}',
                   f'{glyphs.none}{glyphs.none}{glyphs.n}')
    medium['5'] = (f'{glyphs.es}{glyphs.ew}{glyphs.w}',
                   f'{glyphs.ne}{glyphs.ew}{glyphs.sw}',
                   f'{glyphs.ne}{glyphs.ew}{glyphs.nw}')
    medium['6'] = (f'{glyphs.es}{glyphs.ew}{glyphs.sw}',
                   f'{glyphs.nes}{glyphs.ew}{glyphs.sw}',
                   f'{glyphs.ne}{glyphs.ew}{glyphs.nw}')
    medium['7'] = (f'{glyphs.es}{glyphs.ew}{glyphs.sw}',
                   f'{glyphs.none}{glyphs.none}{glyphs.ns}',
                   f'{glyphs.none}{glyphs.none}{glyphs.n}')
    medium['8'] = (f'{glyphs.es}{glyphs.ew}{glyphs.sw}',
                   f'{glyphs.nes}{glyphs.ew}{glyphs.nsw}',
                   f'{glyphs.ne}{glyphs.ew}{glyphs.nw}')
    medium['9'] = (f'{glyphs.es}{glyphs.ew}{glyphs.sw}',
                   f'{glyphs.ne}{glyphs.ew}{glyphs.nsw}',
                   f'{glyphs.ne}{glyphs.ew}{glyphs.nw}')
    medium['?'] = (f'{glyphs.es}{glyphs.ew}{glyphs.sw}',
                   f'{glyphs.none}{glyphs.ew}{glyphs.nw}',
                   f'{glyphs.none}{glyphs.n}{glyphs.none}')
    medium['C'] = (f'{glyphs.es}{glyphs.ew}{glyphs.w}',
                   f'{glyphs.ns}{glyphs.none}{glyphs.none}',
                   f'{glyphs.ne}{glyphs.ew}{glyphs.w}')
    medium['F'] = (f'{glyphs.es}{glyphs.ew}{glyphs.w}',
                   f'{glyphs.nes}{glyphs.ew}{glyphs.none}',
                   f'{glyphs.n}{glyphs.none}{glyphs.none}')
    medium['G'] = (f'{glyphs.es}{glyphs.ew}{glyphs.w}',
                   f'{glyphs.ns}{glyphs.e}{glyphs.sw}',
                   f'{glyphs.ne}{glyphs.ew}{glyphs.nw}')
    medium['H'] = (f'{glyphs.s}{glyphs.none}{glyphs.s}',
                   f'{glyphs.nes}{glyphs.ew}{glyphs.nsw}',
                   f'{glyphs.n}{glyphs.none}{glyphs.n}')
    medium['M'] = (f'{glyphs.es}{glyphs.esw}{glyphs.sw}',
                   f'{glyphs.ns}{glyphs.ns}{glyphs.ns}',
                   f'{glyphs.n}{glyphs.none}{glyphs.n}')
    medium['Z'] = (f'{glyphs.e}{glyphs.ew}{glyphs.sw}',
                   f'{glyphs.es}{glyphs.ew}{glyphs.nw}',
                   f'{glyphs.ne}{glyphs.ew}{glyphs.w}')
    medium['°'] = (f'{glyphs.none}{glyphs.s}{glyphs.none}',
                   f'{glyphs.none}{glyphs.none}{glyphs.none}',
                   f'{glyphs.none}{glyphs.none}{glyphs.none}')

    small  = { key: (key,) for key in medium }

    ret.medium = eva.N(glyphs=medium)
    ret.small  = eva.N(glyphs=small)

    for properties in vars(ret).values():
        properties.fallback = tuple(properties.glyphs[fallback])
        properties.height   = len(properties.fallback)
        properties.width    = len(properties.fallback[0])

    return ret




@M.functools.cache
def build_glyphs():
    ret = eva.N()

    ret.arc      = eva.N()
    ret.arc.all  = '┼'
    ret.arc.none = ' '
    ret.arc.e    = '╶'
    ret.arc.n    = '╵'
    ret.arc.s    = '╷'
    ret.arc.w    = '╴'
    ret.arc.ew   = '─'
    ret.arc.ns   = '│'
    ret.arc.es   = '╭'
    ret.arc.ne   = '╰'
    ret.arc.nw   = '╯'
    ret.arc.sw   = '╮'
    ret.arc.esw  = '┬'
    ret.arc.nes  = '├'
    ret.arc.new  = '┴'
    ret.arc.nsw  = '┤'

    ret.heavy      = eva.N()
    ret.heavy.all  = '╋'
    ret.heavy.none = ' '
    ret.heavy.e    = '╺'
    ret.heavy.n    = '╹'
    ret.heavy.s    = '╻'
    ret.heavy.w    = '╸'
    ret.heavy.ew   = '━'
    ret.heavy.ns   = '┃'
    ret.heavy.es   = '┏'
    ret.heavy.ne   = '┗'
    ret.heavy.nw   = '┛'
    ret.heavy.sw   = '┓'
    ret.heavy.esw  = '┳'
    ret.heavy.nes  = '┣'
    ret.heavy.new  = '┻'
    ret.heavy.nsw  = '┫'

    ret.light    = eva.N(**vars(ret.arc))
    ret.light.es = '┌'
    ret.light.ne = '└'
    ret.light.nw = '┘'
    ret.light.sw = '┐'

    return ret




@M.functools.cache
def build_guides():
    ret    = eva.N()
    ret.h0 = Guide(target=TERMINAL)
    ret.h1 = Guide(target=TERMINAL)
    ret.h2 = Guide(target=TERMINAL)
    ret.h3 = Guide(target=TERMINAL)
    ret.h4 = Guide(target=TERMINAL)
    ret.h5 = Guide(target=TERMINAL)
    ret.h6 = Guide(target=TERMINAL)
    ret.v1 = Guide(target=TERMINAL)
    ret.v2 = Guide(target=TERMINAL)
    ret.v3 = Guide(target=TERMINAL)

    return ret




@M.functools.cache
def build_windows():
    border        = True
    ret           = eva.N()
    ret.cpus      = CPUsWindow(border=border,      target=TERMINAL, title='CPUS')
    ret.current   = CurrentWindow(border=border,   target=TERMINAL, title='CURRENT')
    ret.histogram = HistogramWindow(border=border, target=TERMINAL, title='HISTOGRAM')
    ret.load      = LoadWindow(border=border,      target=TERMINAL, title='LOAD')
    ret.maximum   = MaximumWindow(border=border,   target=TERMINAL, title='MAXIMUM')
    ret.minimum   = MinimumWindow(border=border,   target=TERMINAL, title='MINIMUM')
    ret.smoothed  = SmoothedWindow(border=border,  target=TERMINAL, title='SMOOTHED')

    return ret




@M.functools.cache
def build_zones():
    blue          = eva.N()
    blue.BG_DARK  = BG.DARK_BLUE
    blue.BG_LIGHT = BG.LIGHT_BLUE
    blue.FG_DARK  = FG.DARK_BLUE
    blue.FG_LIGHT = FG.LIGHT_BLUE

    green          = eva.N()
    green.BG_DARK  = BG.DARK_GREEN
    green.BG_LIGHT = BG.LIGHT_GREEN
    green.FG_DARK  = FG.DARK_GREEN
    green.FG_LIGHT = FG.LIGHT_GREEN

    magenta          = eva.N()
    magenta.BG_DARK  = BG.DARK_MAGENTA
    magenta.BG_LIGHT = BG.LIGHT_MAGENTA
    magenta.FG_DARK  = FG.DARK_MAGENTA
    magenta.FG_LIGHT = FG.LIGHT_MAGENTA

    red          = eva.N()
    red.BG_DARK  = BG.DARK_RED
    red.BG_LIGHT = BG.LIGHT_RED
    red.FG_DARK  = FG.DARK_RED
    red.FG_LIGHT = FG.LIGHT_RED

    yellow          = eva.N()
    yellow.BG_DARK  = BG.DARK_YELLOW
    yellow.BG_LIGHT = BG.LIGHT_YELLOW
    yellow.FG_DARK  = FG.DARK_YELLOW
    yellow.FG_LIGHT = FG.LIGHT_YELLOW

    ret         = eva.N()
    ret.highest = eva.N(color=magenta, load=85.0, temperature=80.0)
    ret.high    = eva.N(color=red,     load=50.0, temperature=65.0)
    ret.medium  = eva.N(color=yellow,  load=25.0, temperature=50.0)
    ret.low     = eva.N(color=green,   load=10.0, temperature=30.0)
    ret.lowest  = eva.N(color=blue,    load=0.0,  temperature=0.0)

    return ret




def calc_guide_position(*, guides, index, length, margin):
    guides = eva.normalize_integer(guides, minimum=2)
    length = eva.normalize_integer(length, minimum=1)
    margin = eva.normalize_integer(margin, minimum=0)
    index  = eva.normalize_float(index, maximum=guides, minimum=1.0)

    windows  = guides - 1
    free     = length - (guides * margin)
    step     = margin + (free / windows)
    position = step * (index - 1)

    # prevent corrupting height/width Grid properties with negative positions
    return max(position, 0)




def calc_positions_and_sizes(*, cpus):
    cpus   = eva.normalize_integer(cpus, minimum=1)
    height = TERMINAL.height
    width  = TERMINAL.width
    margin = M.math.sqrt(height * width) / 100 * MARGIN_PERCENTAGE
    margin = eva.normalize_integer(margin, minimum=0)

    # 11 -> gh1 + wsmoothed + gh2 + wload + gh3 + wminimum + gh4 + wcurrent + gh5 + wmaximum + gh6
    if height < 11:
        margin = 0

    gh0 = GUIDES.h0
    gh1 = GUIDES.h1
    gh2 = GUIDES.h2
    gh3 = GUIDES.h3
    gh4 = GUIDES.h4
    gh5 = GUIDES.h5
    gh6 = GUIDES.h6

    gv1 = GUIDES.v1
    gv2 = GUIDES.v2
    gv3 = GUIDES.v3

    wcpus      = WINDOWS.cpus
    wcurrent   = WINDOWS.current
    whistogram = WINDOWS.histogram
    wload      = WINDOWS.load
    wmaximum   = WINDOWS.maximum
    wminimum   = WINDOWS.minimum
    wsmoothed  = WINDOWS.smoothed

    gv1.set_geometry(height=height, width=margin, x=0, y=0)

    gv2.set_geometry(
        height=height,
        width=margin,
        x=calc_guide_position(index=2.4, length=width, margin=margin, guides=3),
        y=0
    )

    gv3.set_geometry(
        height=height,
        width=margin,
        x=calc_guide_position(index=3, length=width, margin=margin, guides=3),
        y=0
    )

    gh1.set_geometry(height=margin, width=width, x=0, y=0)

    gh2.set_geometry(
        height=margin,
        width=(gv3.x + gv3.width) - gv2.x,
        x=gv2.x,
        y=calc_guide_position(index=2, length=height, margin=margin, guides=6)
    )

    gh3.set_geometry(
        height=margin,
        width=gh2.width,
        x=gh2.x,
        y=calc_guide_position(index=3, length=height, margin=margin, guides=6)
    )

    gh4.set_geometry(
        height=margin,
        width=gh2.width,
        x=gh2.x,
        y=calc_guide_position(index=4, length=height, margin=margin, guides=6)
    )

    gh5.set_geometry(
        height=margin,
        width=gh2.width,
        x=gh2.x,
        y=calc_guide_position(index=5, length=height, margin=margin, guides=6)
    )

    gh6.set_geometry(
        height=margin,
        width=width,
        x=0,
        y=calc_guide_position(index=6, length=height, margin=margin, guides=6)
    )

    gh0.set_geometry(
        height=margin,
        width=(gv1.width + gv2.x + gv2.width),
        x=0,
        y=calc_guide_position(index=2, length=height, margin=margin, guides=3)
    )
    gh0.set_geometry(
        # 3 -> border + header + border, 1 -> header
        y=min(gh0.y, cpus + (3 if wcpus.border else 1) + gh1.height)
    )

    if margin:
        gv1.set_geometry(width=gv1.width + margin)
        gv2.set_geometry(width=gv2.width + margin)
        gv3.set_geometry(width=gv3.width + margin, x=gv3.x - margin)

    wcpus.set_geometry(
        height=gh0.y - gh1.y - gh1.height,
        width=gv2.x - gv1.x - gv1.width,
        x=gv1.x + gv1.width,
        y=gh1.y + gh1.height
    )

    whistogram.set_geometry(
        height=gh6.y - gh0.y - gh0.height,
        width=wcpus.width,
        x=wcpus.x,
        y=gh0.y + gh0.height
    )

    wsmoothed.set_geometry(
        height=gh2.y - gh1.y - gh1.height,
        width=gv3.x - gv2.x - gv2.width,
        x=gv2.x + gv2.width,
        y=gh1.y + gh1.height
    )

    wload.set_geometry(
        height=gh3.y - gh2.y - gh2.height,
        width=wsmoothed.width,
        x=wsmoothed.x,
        y=gh2.y + gh2.height
    )

    wminimum.set_geometry(
        height=gh4.y - gh3.y - gh3.height,
        width=wsmoothed.width,
        x=wsmoothed.x,
        y=gh3.y + gh3.height
    )

    wcurrent.set_geometry(
        height=gh5.y - gh4.y - gh4.height,
        width=wsmoothed.width,
        x=wsmoothed.x,
        y=gh4.y + gh4.height
    )

    wmaximum.set_geometry(
        height=gh6.y - gh5.y - gh5.height,
        width=wsmoothed.width,
        x=wsmoothed.x,
        y=gh5.y + gh5.height
    )




def main():
    global EVENTS, FAHRENHEIT, FONTS, GLYPHS, GUIDES, INTERVAL_SNAPSHOT, STRESS, WINDOWS, ZONES

    if arguments := parse_arguments():
        FAHRENHEIT        = arguments.fahrenheit
        INTERVAL_SNAPSHOT = arguments.interval
        STRESS            = arguments.stress

        if arguments.help:
            show_usage_and_exit(error=False)
    else:
        show_usage_and_exit(error=True)

    M.signal.signal(M.signal.SIGHUP,   signal_handler_graceful_exit)
    M.signal.signal(M.signal.SIGINT,   signal_handler_graceful_exit)
    M.signal.signal(M.signal.SIGTERM,  signal_handler_graceful_exit)
    M.signal.signal(M.signal.SIGWINCH, signal_handler_window_changed)

    EVENTS = build_events()
    FONTS  = build_fonts()
    GLYPHS = build_glyphs()
    ZONES  = build_zones()

    GUIDES  = build_guides()
    WINDOWS = build_windows()

    keyboard = M.threading.Thread(daemon=True, target=target_keyboard)
    mouse    = M.threading.Thread(daemon=True, target=target_mouse)
    screen   = M.threading.Thread(daemon=True, target=target_screen)
    snapshot = M.threading.Thread(daemon=True, target=target_snapshot)
    stress   = M.threading.Thread(daemon=True, target=target_stress)
    threads  = (snapshot,) + (keyboard, mouse, stress) + (screen,)

    try:
        TERMINAL.save_cursor()
        TERMINAL.enable_alt_screen()
        TERMINAL.clear_screen()
        TERMINAL.disable_cursor()
        TERMINAL.move_home()

        for thread in threads:
            thread.start()

        EVENTS.bye.wait()

        for event in vars(EVENTS).values():
            event.set()

        for thread in threads:
            thread.join()
    finally:
        TERMINAL.enable_cursor()
        TERMINAL.clear_screen()
        TERMINAL.disable_alt_screen()
        TERMINAL.restore_cursor()




def parse_arguments():
    def argparse_error_handler(message='', /):
        raise M.argparse.ArgumentError(None, message)

    parser       = M.argparse.ArgumentParser(add_help=False, allow_abbrev=False, exit_on_error=False)
    parser.error = argparse_error_handler
    regex        = M.re.compile(r'^(0|[1-9][0-9]*)(\.[0-9]+)?$')

    parser.add_argument('-f', '--fahrenheit', action='count',  default=0)
    parser.add_argument('-h', '--help',       action='count',  default=0)
    parser.add_argument('-i', '--interval',   action='append', default=[])
    parser.add_argument('-s', '--stress',     action='count',  default=0)

    try:
        arguments = parser.parse_args()
        flags     = tuple( value for value in vars(arguments).values() if isinstance(value, int) )
        interval  = arguments.interval

        if any( argument > 1 for argument in flags ):
            argparse_error_handler()

        if len(interval) > 1:
            argparse_error_handler()
        elif not interval:
            interval = INTERVAL_SNAPSHOT
        elif not regex.fullmatch(interval := interval[0]):
            argparse_error_handler()

        ret            = eva.N()
        ret.fahrenheit = bool(arguments.fahrenheit)
        ret.help       = bool(arguments.help)
        ret.interval   = eva.normalize_float(interval, maximum=60.0, minimum=0.0, precision=3)
        ret.stress     = bool(arguments.stress)
    except M.argparse.ArgumentError:
        ret = False

    return ret




def preformat_frequency(value, /, *, compact=False, ghz=False):
    compact   = bool(compact)
    fstr      = '{align}{affix}'
    ghz       = bool(ghz)
    affix     = 'GHz' if ghz else 'MHz'
    divisor   = 1000 if ghz else 1
    maximum   = 9.9 if ghz else 9999.0
    minimum   = 0.0
    padding   = 3 if ghz else 4
    precision = 1 if ghz else 0
    kwargs    = {'maximum': maximum, 'minimum': minimum, 'padding': True, 'precision': precision}
    space     = ' '
    value     = maximum if value is None else float(value) / divisor
    string    = eva.normalize_float(value, **kwargs)

    if compact:
        affix = affix[0]

    ret         = eva.N()
    ret.affix   = affix
    ret.align   = string.rjust(padding, space)
    ret.full    = fstr.format(affix=affix, align=ret.align)
    ret.compact = ret.full.strip(space)
    ret.string  = string
    ret.value   = float(string)

    return ret




def preformat_load(value, /, *, integer=False):
    affix     = '%'
    fstr      = '{align}{affix}'
    integer   = bool(integer)
    maximum   = 100.0
    minimum   = 0.0
    padding   = 3 if integer else 4
    precision = 0 if integer else 1
    kwargs    = {'maximum': maximum, 'minimum': minimum, 'padding': True, 'precision': precision}
    space     = ' '
    value     = maximum if value is None else float(value)
    string    = eva.normalize_float(value, **kwargs)
    value     = float(string)

    if value >= 100 and precision:
        kwargs['precision'] = 0

        string = eva.normalize_float(value, **kwargs)
        value  = float(string)

    ret         = eva.N()
    ret.affix   = affix
    ret.align   = string.rjust(padding, space)
    ret.color   = select_color_by_load(value)
    ret.full    = fstr.format(affix=affix, align=ret.align)
    ret.compact = ret.full.strip(space)
    ret.string  = string
    ret.value   = value

    return ret




def preformat_temperature(value, /, *, integer=False):
    affix     = '°F' if FAHRENHEIT else '°C'
    fstr      = '{align}{affix}'
    integer   = bool(integer)
    maximum   = TEMPERATURE_MAXIMUM
    minimum   = TEMPERATURE_MINIMUM
    padding   = 3 if FAHRENHEIT or integer else 4
    precision = 0 if FAHRENHEIT or integer else 1
    kwargs    = {'maximum': maximum, 'minimum': minimum, 'padding': True, 'precision': precision}
    space     = ' '
    value     = maximum if value is None else float(value)

    if FAHRENHEIT:
        fahrenheit = (value * 1.8) + 32
        string     = eva.normalize_float(fahrenheit, **kwargs)
        value      = float(string)
        celsius    = (value - 32) / 1.8
        celsius    = eva.clamp(celsius, minimum, maximum)
    else:
        string = eva.normalize_float(value, **kwargs)
        value  = float(string)

        if value >= 100 and precision:
            kwargs['precision'] = 0

            string = eva.normalize_float(value, **kwargs)
            value  = float(string)

        celsius = value

    ret         = eva.N()
    ret.affix   = affix
    ret.align   = string.rjust(padding, space)
    ret.celsius = celsius
    ret.color   = select_color_by_temperature(celsius)
    ret.full    = fstr.format(affix=affix, align=ret.align)
    ret.compact = ret.full.strip(space)
    ret.string  = string
    ret.value   = value

    return ret




def preformat_thread(value, /):
    affix     = 'CPU'
    fstr      = '{affix}{align}'
    maximum   = CPU_HIGHEST_THREAD
    minimum   = 0
    padding   = len(str(maximum))
    space     = ' '
    value     = maximum if value is None else eva.clamp(value, minimum, maximum)
    string    = str(value)

    ret         = eva.N()
    ret.affix   = affix
    ret.align   = string.ljust(padding, space)
    ret.full    = fstr.format(affix=affix, align=ret.align)
    ret.compact = ret.full.strip(space)
    ret.string  = string
    ret.value   = value

    return ret




def select_color_by_load(value, /):
    value = max(float(value), 0.0)
    zones = vars(ZONES).values()
    zones = sorted(zones, key=lambda zone: zone.load, reverse=True)
    ret   = next( zone.color for zone in zones if value >= zone.load )

    return ret




def select_color_by_temperature(value, /):
    value = max(float(value), 0.0)
    zones = vars(ZONES).values()
    zones = sorted(zones, key=lambda zone: zone.temperature, reverse=True)
    ret   = next( zone.color for zone in zones if value >= zone.temperature )

    return ret




def show_usage_and_exit(*, error):
    arguments = '[-f|--fahrenheit] [-h|--help] [-i|--interval INTERVAL] [-s|--stress]'
    error     = bool(error)
    code      = int(error)
    printx    = eva.printe if error else eva.printo

    printx(f'version: {VERSION}')
    printx(f'usage:   {arguments}')

    M.sys.exit(code)




def signal_handler_graceful_exit(*args, **kwargs):
    force = False

    # order could matter: first set bye, then wake up waiting threads
    for name in ('bye', 'screen', 'sigwinch', 'stress'):
        if event := getattr(EVENTS, name, False):
            event.set()
        else:
            force = True

    if force:
        M.sys.exit()




def signal_handler_window_changed(*args, **kwargs):
    global SIGWINCH_IDLE

    if SIGWINCH_IDLE and SNAPSHOT:
        screen   = getattr(EVENTS, 'screen',   False)
        sigwinch = getattr(EVENTS, 'sigwinch', False)

        if screen and sigwinch:
            try:
                SIGWINCH_IDLE = False

                # Order could matter: first set sigwinch, then wake up
                # target_screen thread.
                sigwinch.set()
                screen.set()
            finally:
                SIGWINCH_IDLE = True




def target_keyboard():
    try:
        code_arrow_down  = b'\x1B[B'
        code_arrow_left  = b'\x1B[D'
        code_arrow_right = b'\x1B[C'
        code_arrow_up    = b'\x1B[A'
        code_escape      = b'\x1B'
        code_lower_q     = b'q'
        code_lower_r     = b'r'
        code_space       = b' '
        code_upper_q     = code_lower_q.upper()
        code_upper_r     = code_lower_r.upper()
        codes_break      = (code_escape, code_lower_q, code_upper_q)

        dispatcher = {
            code_arrow_down:  WINDOWS.cpus.scroll_down,
            code_arrow_left:  WINDOWS.cpus.select_left,
            code_arrow_right: WINDOWS.cpus.select_right,
            code_arrow_up:    WINDOWS.cpus.scroll_up,
            code_lower_r:     WINDOWS.cpus.toggle_reverse,
            code_space:       toggle_stress,
            code_upper_r:     WINDOWS.cpus.toggle_reverse,
        }

        with eva.Reader() as reader:
            while not EVENTS.bye.is_set():
                chunk = reader.poll()

                if chunk is None:
                    continue
                elif chunk in codes_break or chunk is False:
                    break

                dispatcher.get(chunk, eva.noop)()
    finally:
        EVENTS.bye.set()




def target_mouse():
    try:
        ansi_mouse_off  = '\x1B[?1000l'
        ansi_mouse_on   = '\x1B[?1000h'
        code_wheel_down = b'\x1B\x5B\x4D\x61'
        code_wheel_up   = b'\x1B\x5B\x4D\x60'
        debouncer       = eva.Chrono(timeout=eva.SECOND / 100)
        previous        = None

        dispatcher = {
            code_wheel_down: WINDOWS.cpus.scroll_down,
            code_wheel_up:   WINDOWS.cpus.scroll_up,
        }

        TERMINAL.write(ansi_mouse_on)

        with eva.Reader() as reader:
            while not EVENTS.bye.is_set():
                chunk = reader.poll()

                if chunk is None:
                    continue
                elif chunk is False:
                    break
                elif (chunk := chunk[0:4]) == previous and not debouncer.expired:
                    continue
                else:
                    previous = chunk

                    debouncer.reset()

                dispatcher.get(chunk, eva.noop)()
    finally:
        TERMINAL.write(ansi_mouse_off)
        EVENTS.bye.set()




def target_screen():
    try:
        bye      = EVENTS.bye
        debounce = eva.SECOND / 10
        guides   = vars(GUIDES).values()
        previous = None
        screen   = EVENTS.screen
        sigwinch = EVENTS.sigwinch
        windows  = vars(WINDOWS).values()

        while True:
            screen.wait()

            if bye.is_set():
                break
            else:
                screen.clear()

            snapshot    = SNAPSHOT
            current     = len(snapshot.cpus)
            recalculate = sigwinch.is_set() or previous != current

            if recalculate:
                TERMINAL.clear_screen()

                if sigwinch.is_set():
                    sigwinch.clear()

                    while sigwinch.wait(debounce):
                        if bye.is_set():
                            return
                        else:
                            sigwinch.clear()

                calc_positions_and_sizes(cpus=current)

                for guide in guides:
                    guide.paint(force=True)

            for window in windows:
                window.snapshot = snapshot

                window.paint(force=recalculate)

            previous    = current
            recalculate = False
    finally:
        EVENTS.bye.set()




def target_snapshot():
    try:
        global SNAPSHOT

        by_thread        = lambda cpu: cpu.thread
        calc_timeout     = lambda interval: interval - (clock.elapsed % interval) if interval else 0.0
        clock            = eva.Chrono()
        cpu_fields       = tuple( field.name for field in M.dataclasses.fields(CPUSnapshot) )
        max_temp         = TEMPERATURE_MINIMUM
        min_temp         = TEMPERATURE_MAXIMUM
        smoothed_chrono  = eva.Chrono(timeout=0)
        smoothed_samples = M.collections.deque()
        snapshot_chrono  = eva.Chrono(timeout=0)

        while True:
            while smoothed_samples and smoothed_samples[0].chrono.expired:
                smoothed_samples.popleft()

            temperature = eva.CPU.temperature

            if smoothed_chrono.expired or not smoothed_samples:
                sample = eva.N(chrono=eva.Chrono(timeout=TIMEOUT_SMOOTHED), temperature=temperature)

                smoothed_samples.append(sample)
                smoothed_chrono.reset(timeout=calc_timeout(INTERVAL_SMOOTHED))

            if snapshot_chrono.expired:
                cpus_samples = []
                load         = eva.CPU.load
                max_temp     = max(temperature, max_temp) if BREATHER.expired else temperature
                min_temp     = min(temperature, min_temp)

                for cpu in eva.CPU.get_cpus(auto=True, online=True):
                    kwargs = { field: getattr(cpu, field) for field in cpu_fields }
                    sample = CPUSnapshot(**kwargs)

                    cpus_samples.append(sample)

                cpus_samples.sort(key=by_thread)

                kwargs             = {}
                kwargs['cpus']     = tuple(cpus_samples)
                kwargs['current']  = temperature
                kwargs['load']     = load
                kwargs['maximum']  = max_temp
                kwargs['minimum']  = min_temp
                kwargs['smoothed'] = M.statistics.mean( sample.temperature for sample in smoothed_samples )
                SNAPSHOT           = ProcessorSnapshot(**kwargs)

                snapshot_chrono.reset(timeout=calc_timeout(INTERVAL_SNAPSHOT))
                EVENTS.screen.set()

            if EVENTS.bye.wait(min(smoothed_chrono.remaining, snapshot_chrono.remaining)):
                break
    finally:
        EVENTS.bye.set()




def target_stress():
    if STRESS:
        try:
            context = M.multiprocessing.get_context('spawn')
            tasks   = []

            def append_task(cpu, /):
                ppid    = M.os.getpid()
                stop    = context.Event()
                args    = (cpu, ppid, stop)
                process = context.Process(args=args, daemon=True, target=target_stressor)
                task    = eva.N(cpu=cpu, process=process, stop=stop)

                tasks.append(task)
                process.start()

                with M.contextlib.suppress(OSError):
                    M.os.sched_setaffinity(process.pid, {task.cpu})

            def discard_task(task, /):
                task.stop.set()
                task.process.join()
                tasks.remove(task)

            while True:
                bye = EVENTS.bye.is_set()

                if bye or not EVENTS.stress.is_set():
                    for task in list(tasks):
                        discard_task(task)

                    if bye:
                        break
                    else:
                        EVENTS.stress.wait()

                for task in list(tasks):
                    try:
                        affinity = M.os.sched_getaffinity(task.process.pid)
                    except OSError:
                        affinity = None

                    if affinity != {task.cpu} or not task.process.is_alive():
                        append_task(task.cpu)
                        discard_task(task)

                cpus = set(eva.CPU.get_cpus(online=True)) - set( task.cpu for task in tasks )

                for cpu in cpus:
                    append_task(cpu)
        finally:
            EVENTS.bye.set()




def target_stressor(cpu, ppid, stop, /):
    cpu    = int(cpu)
    mask   = {cpu}
    option = 1 # PR_SET_PDEATHSIG
    pid    = 0
    ppid   = int(ppid)

    M.ctypes.CDLL(None).prctl(option, M.signal.SIGTERM)

    if ppid == M.os.getppid():
        with M.contextlib.suppress(OSError):
            M.os.setsid()
            M.os.sched_setaffinity(pid, mask)

            while not stop.is_set():
                pass




def toggle_stress():
    if STRESS:
        with LOCK:
            if EVENTS.stress.is_set():
                EVENTS.stress.clear()
            else:
                STRESS_CHRONO.reset()
                EVENTS.stress.set()

        EVENTS.screen.set()




@M.dataclasses.dataclass(frozen=True, kw_only=True, slots=True)
class CPUSnapshot:
    # Fields are deliberately not sorted alphabetically. They reflect the column
    # layout of the CPUs window.
    thread:      int
    temperature: float
    load:        float
    minscal:     float
    frequency:   float
    maxscal:     float




@M.dataclasses.dataclass(frozen=True, kw_only=True, slots=True)
class ProcessorSnapshot:
    cpus:     tuple[CPUSnapshot, ...]
    current:  float
    load:     float
    maximum:  float
    minimum:  float
    smoothed: float




class BG(M.enum.Enum):
    DARK_BLACK    = '40'
    DARK_BLUE     = '44'
    DARK_CYAN     = '46'
    DARK_GREEN    = '42'
    DARK_MAGENTA  = '45'
    DARK_RED      = '41'
    DARK_WHITE    = '47'
    DARK_YELLOW   = '43'
    DEFAULT       = '49'
    LIGHT_BLACK   = '100'
    LIGHT_BLUE    = '104'
    LIGHT_CYAN    = '106'
    LIGHT_GREEN   = '102'
    LIGHT_MAGENTA = '105'
    LIGHT_RED     = '101'
    LIGHT_WHITE   = '107'
    LIGHT_YELLOW  = '103'




class FG(M.enum.Enum):
    DARK_BLACK    = '30'
    DARK_BLUE     = '34'
    DARK_CYAN     = '36'
    DARK_GREEN    = '32'
    DARK_MAGENTA  = '35'
    DARK_RED      = '31'
    DARK_WHITE    = '37'
    DARK_YELLOW   = '33'
    DEFAULT       = '39'
    LIGHT_BLACK   = '90'
    LIGHT_BLUE    = '94'
    LIGHT_CYAN    = '96'
    LIGHT_GREEN   = '92'
    LIGHT_MAGENTA = '95'
    LIGHT_RED     = '91'
    LIGHT_WHITE   = '97'
    LIGHT_YELLOW  = '93'




class Base:
    __slots__ = ('_lock',)
    _empty    = ''
    _space    = ' '

    _style_default = {
        'bg':      BG.DEFAULT,
        'blink':   False,
        'dim':     False,
        'fg':      FG.DEFAULT,
        'glyph':   _space,
        'reverse': False,
    }


    def __init__(self, /):
        self._lock = M.threading.RLock()


    @M.contextlib.contextmanager
    def locked(self, /):
        with self._lock:
            yield




class Grid(Base, M.abc.ABC):
    _default_x      = 0
    _default_y      = 0
    _glyph_overflow = '╳'
    _glyphs_noise   = ('░', '▒', '█')
    _minimum_height = 0
    _minimum_width  = 0
    _style_overflow = {**Base._style_default, 'blink': True, 'fg': FG.DARK_RED, 'glyph': _glyph_overflow}
    _style_spacing  = {**Base._style_default}

    _default_geometry = {
        'height': _minimum_height,
        'width':  _minimum_width,
        'x':      _default_x,
        'y':      _default_y,
    }


    @property
    def cells(self, /):
        with self.locked():
            return self._cells


    @property
    def columns(self, /):
        with self.locked():
            return self._columns


    @property
    def height(self, /):
        with self.locked():
            return self._height


    @property
    def rows(self, /):
        with self.locked():
            return self._rows


    @property
    def width(self, /):
        with self.locked():
            return self._width


    @property
    def x(self, /):
        with self.locked():
            return self._x


    @property
    def y(self, /):
        with self.locked():
            return self._y


    def __init__(self, /):
        super().__init__()

        self._cells   = ()
        self._columns = ()
        self._height  = self._default_geometry['height']
        self._rows    = ()
        self._width   = self._default_geometry['width']
        self._x       = self._default_geometry['x']
        self._y       = self._default_geometry['y']


    def apply_default_render(self, /):
        with self.locked():
            for cell in self._cells:
                cell.set_style(**self._style_default)


    def apply_noise_render(self, /):
        with self.locked():
            choice = M.random.choice

            for cell in self._cells:
                dim   = choice((False, True))
                glyph = choice(self._glyphs_noise)
                style = {**self._style_default, 'dim': dim, 'glyph': glyph}

                cell.set_style(**style)


    def apply_overflow_render(self, /):
        with self.locked():
            for cell in self._cells:
                cell.set_style(**self._style_overflow)


    def render(self, /, *, force=False):
        pass


    @M.abc.abstractmethod
    def set_geometry(self, /):
        pass


    def set_style(self, /, *args, **kwargs):
        with self.locked():
            for cell in self._cells:
                cell.set_style(*args, **kwargs)


    def write_text(self, text, /, *, bg=None, blink=None, dim=None, fg=None, reverse=None):
        with self.locked():
            text = str(text)

            for char, cell in zip(text, self._cells):
                cell.set_style(bg=bg, blink=blink, dim=dim, fg=fg, reverse=reverse, glyph=char)




class Canvas(Grid):
    @property
    def target(self, /):
        with self.locked():
            return self._target


    def __init__(self, /, *, height=None, target, width=None, x=None, y=None):
        super().__init__()

        if isinstance(target, Canvas):
            del self._lock
        elif not isinstance(target, eva.Terminal):
            raise TypeError

        self._positions = {}
        self._queue     = set()
        self._target    = target

        __class__.set_geometry(self, height=height, width=width, x=x, y=y)


    def _print_on_target(self, /, *, force):
        force    = bool(force)
        cells    = self._cells if force else self._queue
        output   = []
        target   = self._target
        height   = target.height
        terminal = isinstance(target, eva.Terminal)
        width    = target.width

        for cell in cells:
            if force or cell.dirty:
                cell.dirty = False
            else:
                continue

            x, y = self._positions[cell]

            x = x + self._x
            y = y + self._y

            if x < 0 or y < 0:
                continue
            elif x >= width or y >= height:
                continue

            if terminal:
                output.append(f'\x1B[{y + 1};{x + 1}H')
                output.append(cell.sequence)
            else:
                # Private access is preferred for performance: not considered to
                # violate the public abstraction since both objects are the same
                # class.
                target._columns[x][y].copy_style_from(cell)

        self._queue.clear()

        if terminal:
            output = self._empty.join(output)

            target.write(output)


    @M.contextlib.contextmanager
    def locked(self, /):
        lock = self._lock if hasattr(self, '_lock') else self._target.locked()

        with lock:
            yield


    def notify(self, cell, /):
        with self.locked():
            if cell in self._positions:
                self._queue.add(cell)


    def paint(self, /, *, force=False):
        with self.locked():
            force = bool(force)

            self.render(force=force)
            self._print_on_target(force=force)


    def set_geometry(self, /, *, height=None, width=None, x=None, y=None):
        with self.locked():
            height = self._height if height is None else eva.normalize_integer(height)
            width  = self._width  if width  is None else eva.normalize_integer(width)
            x      = self._x      if x      is None else eva.normalize_integer(x)
            y      = self._y      if y      is None else eva.normalize_integer(y)

            if height < 0:
                height = max(self._target.height + height, self._minimum_height)

            if width < 0:
                width = max(self._target.width + width, self._minimum_width)

            self._x = x
            self._y = y

            if height == self._height and width == self._width:
                return

            cells     = []
            columns   = []
            positions = {}
            rows      = []

            for x in range(width):
                column = self._columns[x] if x < len(self._columns) else ()
                column = list(column[0:height])

                while len(column) < height:
                    cell = Cell(target=self)

                    column.append(cell)

                columns.append(tuple(column))

            for y in range(height):
                row = []

                for x, column in enumerate(columns):
                    cell            = column[y]
                    positions[cell] = (x, y)

                    cells.append(cell)
                    row.append(cell)

                rows.append(tuple(row))

            self._cells     = tuple(cells)
            self._columns   = tuple(columns)
            self._height    = height
            self._positions = positions
            self._queue     = { cell for cell in cells if cell.dirty }
            self._rows      = tuple(rows)
            self._width     = width




class Cell(Base):
    __slots__ = (
        '_bg',
        '_blink',
        '_dim',
        '_dirty',
        '_fg',
        '_glyph',
        '_reverse',
        '_sequence',
        '_target',
    )

    _glyph_replacement = '\uFFFD'


    @property
    def bg(self, /):
        with self.locked():
            return self._bg


    @property
    def blink(self, /):
        with self.locked():
            return self._blink


    @property
    def dim(self, /):
        with self.locked():
            return self._dim


    @property
    def dirty(self, /):
        with self.locked():
            return self._dirty


    @property
    def fg(self, /):
        with self.locked():
            return self._fg


    @property
    def glyph(self, /):
        with self.locked():
            return self._glyph


    @property
    def reverse(self, /):
        with self.locked():
            return self._reverse


    @property
    def sequence(self, /):
        with self.locked():
            if self._sequence is None:
                codes     = []
                prefix    = '\x1B['
                reset     = '\x1B[0m'
                separator = ';'
                suffix    = 'm'

                if self._reverse:
                    codes.append('7')

                if self._dim:
                    codes.append('2')

                if self._blink:
                    codes.append('5')

                codes.append(self._bg.value)
                codes.append(self._fg.value)

                self._sequence = prefix + separator.join(codes) + suffix + self._glyph + reset

            return self._sequence


    @property
    def target(self, /):
        with self.locked():
            return self._target


    @bg.setter
    def bg(self, value, /):
        if isinstance(value, BG):
            self.set_style(bg=value)
        else:
            raise TypeError


    @blink.setter
    def blink(self, value, /):
        self.set_style(blink=bool(value))


    @dim.setter
    def dim(self, value, /):
        self.set_style(dim=bool(value))


    @dirty.setter
    def dirty(self, value, /):
        with self._target.locked():
            with self.locked():
                value = bool(value)

                if value != self._dirty:
                    self._dirty = value

                    if value:
                        self._target.notify(self)


    @fg.setter
    def fg(self, value, /):
        if isinstance(value, FG):
            self.set_style(fg=value)
        else:
            raise TypeError


    @glyph.setter
    def glyph(self, value, /):
        self.set_style(glyph=str(value))


    @reverse.setter
    def reverse(self, value, /):
        self.set_style(reverse=bool(value))


    def __init__(self, /, *, bg=None, blink=None, dim=None, fg=None, glyph=None, reverse=None, target):
        super().__init__()

        if not isinstance(target, Canvas):
            raise TypeError

        self._bg       = self._style_default['bg']
        self._blink    = self._style_default['blink']
        self._dim      = self._style_default['dim']
        self._dirty    = True
        self._fg       = self._style_default['fg']
        self._glyph    = self._style_default['glyph']
        self._reverse  = self._style_default['reverse']
        self._sequence = None
        self._target   = target

        __class__.set_style(self, bg=bg, blink=blink, dim=dim, fg=fg, glyph=glyph, reverse=reverse)


    def copy_style_from(self, cell, /, *, bg=None, blink=None, dim=None, fg=None, glyph=None, reverse=None):
        if not isinstance(cell, Cell):
            raise TypeError

        # Private access is preferred for performance: not considered to violate
        # the public abstraction since both objects are the same class.
        with cell.locked():
            new = {
                'bg':      cell._bg      if bg      is None else bg,
                'blink':   cell._blink   if blink   is None else blink,
                'dim':     cell._dim     if dim     is None else dim,
                'fg':      cell._fg      if fg      is None else fg,
                'glyph':   cell._glyph   if glyph   is None else glyph,
                'reverse': cell._reverse if reverse is None else reverse,
            }

        with self.locked():
            old = {
                'bg':      self._bg,
                'blink':   self._blink,
                'dim':     self._dim,
                'fg':      self._fg,
                'glyph':   self._glyph,
                'reverse': self._reverse,
            }

            if old != new:
                self.set_style(**new)


    def set_style(self, /, *, bg=None, blink=None, dim=None, fg=None, glyph=None, reverse=None):
        with self._target.locked():
            with self.locked():
                notify = False

                if bg is not None:
                    if not isinstance(bg, BG):
                        raise TypeError

                    if bg != self._bg:
                        notify   = True
                        self._bg = bg

                if blink is not None:
                    blink = bool(blink)

                    if blink != self._blink:
                        notify      = True
                        self._blink = blink

                if dim is not None:
                    dim = bool(dim)

                    if dim != self._dim:
                        notify    = True
                        self._dim = dim

                if fg is not None:
                    if not isinstance(fg, FG):
                        raise TypeError

                    if fg != self._fg:
                        notify   = True
                        self._fg = fg

                if glyph is not None:
                    glyph = str(glyph)
                    glyph = glyph[0] if glyph else self._space

                    if glyph.isspace():
                        glyph = self._space
                    elif not glyph.isprintable():
                        glyph = self._glyph_replacement

                    if glyph != self._glyph:
                        notify      = True
                        self._glyph = glyph

                if reverse is not None:
                    reverse = bool(reverse)

                    if reverse != self._reverse:
                        notify        = True
                        self._reverse = reverse

                if notify:
                    self._dirty    = True
                    self._sequence = None

                    self._target.notify(self)




class Guide(Canvas):
    def render(self, /, *, force=False):
        self.set_style(**self._style_spacing)




class View(Grid):
    @property
    def target(self, /):
        with self.locked():
            return self._target


    def __init__(self, /, *, height=None, target, width=None, x=None, y=None):
        super().__init__()

        if not isinstance(target, (Canvas, View)):
            raise TypeError

        del self._lock

        self._target = target

        __class__.set_geometry(self, height=height, width=width, x=x, y=y)


    @M.contextlib.contextmanager
    def locked(self, /):
        with self._target.locked():
            yield


    def set_geometry(self, /, *, height=None, width=None, x=None, y=None):
        with self.locked():
            height = self._height if height is None else eva.normalize_integer(height)
            width  = self._width  if width  is None else eva.normalize_integer(width)
            x      = self._x      if x      is None else eva.normalize_integer(x)
            y      = self._y      if y      is None else eva.normalize_integer(y)

            if height < 0:
                height = max(self._target.height + height, self._minimum_height)

            if width < 0:
                width = max(self._target.width + width, self._minimum_width)

            self._height = height
            self._width  = width
            self._x      = x
            self._y      = y

            bottom = eva.clamp(y + height, 0, self._target.height)
            left   = eva.clamp(x,          0, self._target.width)
            right  = eva.clamp(x + width,  0, self._target.width)
            top    = eva.clamp(y,          0, self._target.height)

            cells   = []
            columns = []
            rows    = []

            for column in self._target.columns[left:right]:
                columns.append(column[top:bottom])

            for row in self._target.rows[top:bottom]:
                row = row[left:right]

                cells.extend(row)
                rows.append(row)

            self._cells   = tuple(cells)
            self._columns = tuple(columns)
            self._rows    = tuple(rows)




class Window(Canvas):
    _mask_down    = 0b01
    _mask_empty   = 0b00
    _mask_up      = 0b10
    _mask_both    = _mask_down | _mask_up
    _glyph_thumb  = '█'
    _glyphs_mask  = {_mask_both: '↕', _mask_down: '↓', _mask_empty: '┆', _mask_up: '↑'}
    _style_border = {**Base._style_default, 'dim': True}
    _style_scroll = {**Base._style_default}
    _style_title  = {**Base._style_default}


    @property
    def border(self, /):
        with self.locked():
            return self._border


    @property
    def snapshot(self, /):
        with self.locked():
            return self._snapshot


    @property
    def title(self, /):
        with self.locked():
            return self._title_string


    @border.setter
    def border(self, value, /):
        with self.locked():
            value = bool(value)

            if value != self._border:
                self._border       = value
                self._redecoration = True

                self.set_geometry()


    @snapshot.setter
    def snapshot(self, value, /):
        with self.locked():
            if not isinstance(value, ProcessorSnapshot):
                raise TypeError

            self._snapshot = value


    @title.setter
    def title(self, value, /):
        with self.locked():
            value = eva.normalize_text(value, full=True)

            if value != self._title_string:
                self._redecoration = True
                self._title_string = value

                self._adjust_title()


    def __init__(self, /, *args, border=False, title=None, **kwargs):
        super().__init__(*args, **kwargs)

        self._border        = bool(border)
        self._border_bottom = View(target=self)
        self._border_left   = View(target=self)
        self._border_right  = View(target=self)
        self._border_top    = View(target=self)
        self._padding_left  = View(target=self)
        self._padding_right = View(target=self)
        self._redecoration  = True
        self._scroll        = View(target=self)
        self._scroll_index  = 0
        self._snapshot      = None
        self._title         = View(target=self._border_top)
        self._title_string  = self._empty
        self._viewport      = View(target=self)
        self._inner         = View(target=self._viewport)

        self.title = self._empty if title is None else title

        __class__.set_geometry(self)


    def _adjust_border(self, /):
        geometry_bottom = self._default_geometry
        geometry_left   = self._default_geometry
        geometry_right  = self._default_geometry
        geometry_top    = self._default_geometry

        if self._border:
            height = self._height
            width  = self._width

            geometry_bottom = {'height': 1,      'width': -2, 'x': 1,         'y': height - 1}
            geometry_left   = {'height': height, 'width': 1,  'x': 0,         'y': 0}
            geometry_right  = {'height': height, 'width': 1,  'x': width - 1, 'y': 0}
            geometry_top    = {'height': 1,      'width': -2, 'x': 1,         'y': 0}

        self._border_bottom.set_geometry(**geometry_bottom)
        self._border_left.set_geometry(**geometry_left)
        self._border_right.set_geometry(**geometry_right)
        self._border_top.set_geometry(**geometry_top)


    def _adjust_padding(self, /):
        geometry_left  = self._default_geometry
        geometry_right = self._default_geometry

        if self._border:
            height = self._height
            width  = self._width

            geometry_left  = {'height': height - 2, 'width': 1, 'x': 1,         'y': 1}
            geometry_right = {'height': height - 2, 'width': 1, 'x': width - 2, 'y': 1}

        self._padding_left.set_geometry(**geometry_left)
        self._padding_right.set_geometry(**geometry_right)


    def _adjust_scroll(self, /):
        if self._border:
            self._scroll.set_geometry(height=-2, width=1, x=self._width - 1, y=1)
        else:
            self._scroll.set_geometry(**self._default_geometry)


    def _adjust_scroll_index(self, scroll, /):
        minimum = 0
        maximum = max(self._inner.height - self._viewport.height, minimum)

        scroll = eva.normalize_integer(scroll)
        scroll = self._scroll_index + scroll
        scroll = eva.clamp(scroll, minimum, maximum)

        if self._scroll_index != scroll:
            self._redecoration = True
            self._scroll_index = scroll

            return True
        else:
            return False


    def _adjust_title(self, /):
        border   = self._border_top
        geometry = {**self._default_geometry}

        if self._border:
            text = self._space + self._title_string + self._space
            text = text[0:border.width]

            if text:
                text     = text[0:-1] + self._space
                length   = len(text)
                x        = (border.width - length) // 2
                geometry = {'height': 1, 'width': length, 'x': x, 'y': 0}

        self._title.set_geometry(**geometry)


    def _render_helper_border(self, /):
        bottom     = self._border_bottom
        glyphs     = GLYPHS.arc
        glyphless  = { k: v for k, v in self._style_border.items() if k != 'glyph' }
        left       = self._border_left
        right      = self._border_right
        top        = self._border_top
        horizontal = glyphs.ew * top.width
        vertical   = glyphs.ns * left.height

        if not bottom.cells or not left.cells or not right.cells or not top.cells:
            return

        bottom.write_text(horizontal, **glyphless)
        left.write_text(vertical,     **glyphless)
        right.write_text(vertical,    **glyphless)
        top.write_text(horizontal,    **glyphless)

        left.cells[0].glyph   = glyphs.es
        left.cells[-1].glyph  = glyphs.ne
        right.cells[0].glyph  = glyphs.sw
        right.cells[-1].glyph = glyphs.nw


    def _render_helper_padding(self, /):
        left  = self._padding_left
        right = self._padding_right
        style = self._style_spacing

        if not left.cells or not right.cells:
            return

        left.set_style(**style)
        right.set_style(**style)


    def _render_helper_scroll(self, /):
        first_position       = 0
        glyphless_border     = { k: v for k, v in self._style_border.items() if k != 'glyph' }
        glyphless_scroll     = { k: v for k, v in self._style_scroll.items() if k != 'glyph' }
        index                = self._scroll_index
        inner                = self._inner
        second_position      = 1
        scroll               = self._scroll
        viewport             = self._viewport
        last_position        = viewport.height - 1
        penultimate_position = viewport.height - 2
        steps                = inner.height - viewport.height

        if not scroll.cells or inner.height <= viewport.height:
            return

        for y, cell in enumerate(scroll.cells):
            bitmask = self._mask_empty

            if y == first_position and index > first_position:
                bitmask = bitmask | self._mask_up

            if y == last_position and index < steps:
                bitmask = bitmask | self._mask_down

            glyph     = self._glyphs_mask[bitmask]
            glyphless = glyphless_scroll if bitmask else glyphless_border

            cell.set_style(**glyphless, glyph=glyph)

        if viewport.height > 2:
            maximum  = last_position if index == steps else penultimate_position
            minimum  = second_position if index else first_position
            position = (index / steps) * last_position
            position = eva.normalize_integer(position, maximum=maximum, minimum=minimum)
            thumb    = scroll.cells[position]

            thumb.set_style(**glyphless_scroll, glyph=self._glyph_thumb)


    def _render_helper_title(self, /):
        glyphless = { k: v for k, v in self._style_title.items() if k != 'glyph' }
        text      = self._space + self._title_string + self._space
        title     = self._title

        if not title.cells:
            return

        title.write_text(text, **glyphless)

        title.cells[0].set_style(**self._style_spacing)
        title.cells[-1].set_style(**self._style_spacing)


    def paint(self, /, *, force=False):
        with self.locked():
            force = bool(force)

            if self._viewport.cells:
                if force or self._redecoration:
                    self._render_helper_border()
                    self._render_helper_padding()
                    self._render_helper_scroll()
                    self._render_helper_title()

                    self._redecoration = False

                self.render(force=force)
            else:
                self.apply_overflow_render()

            self._print_on_target(force=force)


    def render(self, /, *, force=False):
        self.apply_noise_render()


    def scroll_down(self, /):
        with self.locked():
            if self._adjust_scroll_index(1):
                self.paint()


    def scroll_up(self, /):
        with self.locked():
            if self._adjust_scroll_index(-1):
                self.paint()


    def set_geometry(self, /, *args, **kwargs):
        with self.locked():
            super().set_geometry(*args, **kwargs)

            get_viewport_size = lambda: (viewport.height, viewport.width)
            inner             = self._inner
            viewport          = self._viewport
            previous          = get_viewport_size()

            if self._border:
                geometry = {'height': -2, 'width': -4, 'x': 2, 'y': 1}
            else:
                geometry = {'height': self._height, 'width': self._width, 'x': 0, 'y': 0}

            viewport.set_geometry(**geometry)

            if previous == get_viewport_size():
                return

            self._adjust_border()
            self._adjust_padding()
            self._adjust_scroll()
            self._adjust_title()
            inner.set_geometry(height=viewport.height, width=viewport.width, x=0, y=0)

            self._redecoration = True




class CPUsWindow(Window):
    _fields_cpu         = tuple( field.name for field in M.dataclasses.fields(CPUSnapshot) )
    _fields_sortables   = _fields_cpu[1:]
    _focus_placeholder  = 'thread'
    _glyph_bar_center   = '╳'
    _glyph_bar_fill     = '▮'
    _glyph_bar_lower    = '╱'
    _glyph_bar_upper    = '╲'
    _glyph_sort_default = '▲'
    _glyph_sort_reverse = '▼'
    _messages_monitor   = ('monitor mode', 'monitor', 'm')
    _messages_off       = ('stress test OFF', 'OFF')
    _messages_on        = ('stress test ON ({minutes}m {seconds}s)', '{minutes}m {seconds}s', 'ON')
    _style_blank        = {**Base._style_default, 'fg': FG.LIGHT_BLACK}
    _style_messages_off = {**Base._style_default, 'fg': FG.DARK_YELLOW}
    _style_messages_on  = {**Base._style_default, 'blink': True, 'fg': FG.DARK_RED}


    @Window.snapshot.setter
    def snapshot(self, value, /):
        with self.locked():
            previous = len(self._snapshot.cpus) if self._snapshot else None

            Window.snapshot.fset(self, value)

            current = len(self._snapshot.cpus)

            if previous != current:
                self._adjust_inner_height()


    def __init__(self, /, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._blank_bar   = Canvas(target=self)
        self._fields      = M.collections.deque(self._fields_cpu)
        self._label_left  = View(target=self._viewport)
        self._label_right = View(target=self._viewport)
        self._reverse     = True

        __class__.set_geometry(self)


    def _adjust_blank_bar(self, /):
        bar       = self._blank_bar
        layout    = self._layout
        width     = layout.rows[0].bar.width if layout else 0
        center    = self._glyph_bar_center if width % 2 else self._empty
        glyphless = { k: v for k, v in self._style_blank.items() if k != 'glyph' }
        lower     = self._glyph_bar_lower * M.math.floor(width / 2)
        upper     = self._glyph_bar_upper * M.math.floor(width / 2)
        text      = lower + center + upper

        bar.set_geometry(height=1, width=width)
        bar.write_text(text, **glyphless)


    def _adjust_inner_height(self, /):
        if self._snapshot:
            header = 1 if self._viewport.height > 1 else 0
            height = len(self._snapshot.cpus) + header

            self._inner.set_geometry(height=height)
            self._adjust_scroll_index(0)


    def _adjust_labels(self, /):
        focus          = self._fields[0]
        geometry_left  = self._default_geometry
        geometry_right = self._default_geometry
        layout         = self._layout
        header         = layout.rows[0] if layout and len(layout.rows) > 1 else eva.N()
        names          = tuple(vars(header).keys())

        if names:
            if focus in names and (index := names.index(focus)):
                before = names[:index]
                after  = names[index + 1:]

                if before:
                    before        = getattr(header, before[-1])
                    geometry_left = {'height': 1, 'width': before.x + before.width, 'x': 0, 'y': 0}

                if after:
                    after          = getattr(header, after[0])
                    geometry_right = {'height': 1, 'width': -after.x, 'x': after.x, 'y': 0}
            else:
                geometry_right = {'height': 1, 'width': self._viewport.width, 'x': 0, 'y': 0}

        self._label_left.set_geometry(**geometry_left)
        self._label_right.set_geometry(**geometry_right)


    def _adjust_layout(self, /):
        by_length    = lambda layout: layout.minimum
        empty        = self._empty
        fstr         = '{thread} {temperature} {load} {minscal} {frequency} {maxscal}{sep}{bar}'
        self._layout = False
        viewport     = self._viewport

        if 0 in (viewport.height, viewport.width):
            return

        layouts = (
            eva.N(compact=False, ghz=False, integer=False), # CPU0 99.9°C 99.9% 9999MHz 9999MHz 9999MHz
            eva.N(compact=True,  ghz=False, integer=False), # CPU0 99.9°C 99.9% 9999M 9999M 9999M
            eva.N(compact=True,  ghz=False, integer=True),  # CPU0 100°C 100% 9999M 9999M 9999M
            eva.N(compact=True,  ghz=True,  integer=True),  # CPU0 100°C 100% 9.9G 9.9G 9.9G
        )

        for layout in layouts:
            frequency = preformat_frequency(None, ghz=layout.ghz, compact=layout.compact).full

            kwargs = {
                'bar':         empty,
                'frequency':   frequency,
                'load':        preformat_load(None, integer=layout.integer).full,
                'maxscal':     frequency,
                'minscal':     frequency,
                'sep':         empty,
                'temperature': preformat_temperature(None, integer=layout.integer).full,
                'thread':      preformat_thread(None).full,
            }

            length            = { name: len(value) for name, value in kwargs.items() }
            layout.length     = eva.N(**length)
            layout.minimum    = len(fstr.format(**kwargs))
            free              = viewport.width - layout.minimum
            layout.length.bar = max(free - 1, 0) # 1 -> sep
            layout.length.sep = eva.clamp(free, minimum=0, maximum=1)

        for layout in sorted(layouts, key=by_length, reverse=True):
            if layout.minimum <= viewport.width:
                break
        else:
            return

        names = self._fields_cpu + ('bar',)
        rows  = []

        for y in range(viewport.height):
            row = eva.N()
            x   = 0

            for name in names:
                width = getattr(layout.length, name)
                view  = View(height=1, target=viewport, width=width, x=x, y=y)

                setattr(row, name, view)

                # 2 -> sep + space, 1 -> space
                gap = 2 if not x and layout.length.bar < layout.length.sep else 1
                x   = x + width + gap

            rows.append(row)

        self._layout = eva.N(
            compact=layout.compact,
            ghz=layout.ghz,
            integer=layout.integer,
            rows=tuple(rows),
        )


    def _render_helper_bar(self, /, *, row, snapshot):
        if not isinstance(row, tuple) or not isinstance(snapshot, CPUSnapshot):
            raise TypeError

        blank             = self._blank_bar.cells
        load              = preformat_load(snapshot.load)
        temperature       = preformat_temperature(snapshot.temperature)
        width             = len(row)
        load_cells        = eva.normalize_integer(load.value / 100 * width)
        temperature_cells = eva.normalize_integer(min(temperature.celsius, 100) / 100 * width)

        for x, source, destination, in zip(range(width), blank, row):
            style = {}

            if temperature_cells > x:
                style['bg']    = temperature.color.BG_DARK
                style['glyph'] = self._space

            if load_cells > x:
                style['fg']    = load.color.FG_LIGHT
                style['glyph'] = self._glyph_bar_fill

            destination.copy_style_from(source, **style)


    def _render_helper_header(self, /):
        focus   = self._fields[0]
        inner   = self._inner
        layout  = self._layout
        left    = self._label_left
        minutes = 0
        right   = self._label_right
        seconds = 0
        space   = self._space
        views   = layout.rows[0] if layout and len(layout.rows) > 1 else False

        if views:
            kwargs    = { name: getattr(views, name) for name in self._fields_sortables }
            sortables = eva.N(**kwargs)

            for cell in inner.rows[0]:
                cell.set_style(**self._style_default)
        else:
            return

        if hasattr(sortables, focus):
            style     = {**self._style_default, 'reverse': True}
            glyphless = { k: v for k, v in style.items() if k != 'glyph' }
            view      = getattr(sortables, focus)
            text      = self._glyph_sort_reverse if self._reverse else self._glyph_sort_default
            text      = text.center(view.width, space)

            view.write_text(text, **glyphless)

        if not STRESS:
            messages = self._messages_monitor
            style    = self._style_default
        elif EVENTS.stress.is_set():
            messages = self._messages_on
            seconds  = eva.normalize_integer(STRESS_CHRONO.elapsed)
            minutes  = seconds // 60
            seconds  = seconds % 60
            style    = self._style_messages_on
        else:
            messages = self._messages_off
            style    = self._style_messages_off

        for message in messages:
            message = message.format(minutes=minutes, seconds=seconds)
            length  = len(message)

            if right.width >= length and right.width >= left.width:
                label = right
            elif left.width >= length:
                label = left
            else:
                continue

            glyphless = { k: v for k, v in style.items() if k != 'glyph' }
            x         = (inner.width - length) // 2
            padding   = space * max(x - label.x, 0)
            text      = padding + message
            text      = text.ljust(label.width, space)
            text      = text[-label.width:]

            label.write_text(text, **glyphless)

            break


    def render(self, /, *, force=False):
        with self.locked():
            by_focus      = lambda cpu: getattr(cpu, focus)
            cpus          = self._snapshot.cpus
            focus         = self._fields[0]
            force         = bool(force)
            layout        = self._layout
            needs_reverse = lambda cells, value: cells and cells[0].reverse != value

            if force:
                if layout:
                    self._inner.apply_default_render()

                    fields = {
                        'frequency':   preformat_frequency(None, compact=layout.compact, ghz=layout.ghz),
                        'load':        preformat_load(None, integer=layout.integer),
                        'maxscal':     preformat_frequency(None, compact=layout.compact, ghz=layout.ghz),
                        'minscal':     preformat_frequency(None, compact=layout.compact, ghz=layout.ghz),
                        'temperature': preformat_temperature(None, integer=layout.integer),
                        'thread':      preformat_thread(None),
                    }

                    for row in layout.rows:
                        for name in fields:
                            value  = fields[name]
                            affix  = value.affix
                            length = len(affix)
                            view   = getattr(row, name)
                            cells  = reversed(view.cells) if value.full.endswith(affix) else view.cells

                            for cell in M.itertools.islice(cells, length):
                                cell.set_style(dim=True)
                else:
                    self.apply_overflow_render()

            if not layout:
                return

            if focus != self._focus_placeholder:
                cpus = sorted(cpus, key=by_focus, reverse=self._reverse)

            self._render_helper_header()

            for y, row in enumerate(layout.rows[1:] if len(layout.rows) > 1 else layout.rows):
                cpu         = cpus[self._scroll_index + y]
                frequency   = preformat_frequency(cpu.frequency, compact=layout.compact, ghz=layout.ghz)
                load        = preformat_load(cpu.load, integer=layout.integer)
                maxscal     = preformat_frequency(cpu.maxscal, compact=layout.compact, ghz=layout.ghz)
                minscal     = preformat_frequency(cpu.minscal, compact=layout.compact, ghz=layout.ghz)
                temperature = preformat_temperature(cpu.temperature, integer=layout.integer)
                thread      = preformat_thread(cpu.thread)

                row.frequency.write_text(frequency.full)
                row.load.write_text(load.full, fg=load.color.FG_DARK)
                row.maxscal.write_text(maxscal.full)
                row.minscal.write_text(minscal.full)
                row.temperature.write_text(temperature.full, fg=temperature.color.FG_DARK)
                row.thread.write_text(thread.full)

                for name in self._fields_sortables:
                    value = name == focus
                    view  = getattr(row, name)

                    if needs_reverse(view.cells, value):
                        for cell in view.cells:
                            cell.set_style(reverse=value)

                self._render_helper_bar(row=row.bar.cells, snapshot=cpu)


    def select_left(self, /):
        with self.locked():
            self._fields.rotate(1)
            self._adjust_labels()
            self.paint()


    def select_right(self, /):
        with self.locked():
            self._fields.rotate(-1)
            self._adjust_labels()
            self.paint()


    def set_geometry(self, /, *args, **kwargs):
        with self.locked():
            super().set_geometry(*args, **kwargs)
            self._adjust_inner_height()
            self._adjust_layout()
            self._adjust_blank_bar()
            self._adjust_labels()


    def toggle_reverse(self, /):
        with self.locked():
            self._reverse = not self._reverse
            self.paint()




class HistogramWindow(Window):
    _glyph_column_center = '╳'
    _glyph_column_lower  = '╲'
    _glyph_column_upper  = '╱'
    _style_blank         = {**Base._style_default, 'fg': FG.LIGHT_BLACK}


    @Window.snapshot.setter
    def snapshot(self, value, /):
        with self.locked():
            Window.snapshot.fset(self, value)

            cache    = self._cache
            snapshot = self.snapshot

            if not cache or cache[-1] != snapshot:
                cache.append(snapshot)


    def __init__(self, /, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._blank_column = Canvas(target=self)
        self._cache        = M.collections.deque(maxlen=0)

        __class__.set_geometry(self)


    def _adjust_blank_column(self, /):
        column    = self._blank_column
        height    = self._viewport.height
        center    = self._glyph_column_center if height % 2 else self._empty
        glyphless = { k: v for k, v in self._style_blank.items() if k != 'glyph' }
        lower     = self._glyph_column_lower * M.math.floor(height / 2)
        upper     = self._glyph_column_upper * M.math.floor(height / 2)
        text      = upper + center + lower

        column.set_geometry(height=height, width=1)
        column.write_text(text, **glyphless)


    def _adjust_cache_length(self, /):
        cache = self._cache

        if cache.maxlen is not None:
            maxlen = max(cache.maxlen, self._viewport.width)

            if maxlen > cache.maxlen:
                self._cache = M.collections.deque(cache, maxlen=maxlen)


    def _render_helper_column(self, /, *, column, snapshot):
        if not isinstance(column, tuple) or not isinstance(snapshot, ProcessorSnapshot):
            raise TypeError

        blank             = reversed(self._blank_column.cells)
        column            = reversed(column)
        glyphs            = GLYPHS.heavy
        height            = self._inner.height
        load              = preformat_load(snapshot.load)
        load_cells        = load.value / 100 * height
        temperature       = preformat_temperature(snapshot.current)
        temperature_cells = eva.normalize_integer(min(temperature.celsius, 100) / 100 * height)

        for y, source, destination in zip(range(height), blank, column):
            style = {}

            if temperature_cells > y:
                style['bg']    = temperature.color.BG_DARK
                style['glyph'] = self._space

            if eva.normalize_integer(load_cells) > y:
                style['fg']    = load.color.FG_LIGHT
                style['glyph'] = glyphs.ns
            elif M.math.ceil(load_cells) > y:
                style['fg']    = load.color.FG_LIGHT
                style['glyph'] = glyphs.s

            destination.copy_style_from(source, **style)


    def render(self, /, *, force=False):
        with self.locked():
            force   = bool(force)
            inner   = self._inner
            columns = inner.columns

            if force:
                cache = reversed(self._cache)

                for x in range(inner.width - 1, -1, -1):
                    column   = columns[x]
                    snapshot = next(cache, False)

                    if snapshot:
                        self._render_helper_column(column=column, snapshot=snapshot)
                    else:
                        for source, destination in zip(self._blank_column.cells, column):
                            destination.copy_style_from(source)
            elif columns:
                for right, left in zip(columns[1:], columns):
                    for source, destination in zip(right, left):
                        destination.copy_style_from(source)

                self._render_helper_column(column=columns[-1], snapshot=self.snapshot)


    def set_geometry(self, /, *args, **kwargs):
        with self.locked():
            super().set_geometry(*args, **kwargs)
            self._adjust_blank_column()
            self._adjust_cache_length()




class ValueWindow(Window):
    _class_lock  = M.threading.RLock()
    _common_font = False
    _instances   = M.weakref.WeakSet()


    def __init__(self, /, *args, **kwargs):
        super().__init__(*args, **kwargs)

        with self.locked():
            __class__._instances.add(self)
            __class__._calc_common_font()


    @staticmethod
    def _calc_common_font():
        __class__._common_font = False

        by_size         = lambda font: (font.height, font.width)
        fonts           = sorted(vars(FONTS).values(), key=by_size, reverse=True)
        instances       = tuple(__class__._instances)
        max_load        = len(preformat_load(None).full)
        max_temperature = len(preformat_temperature(None).full)
        max_value       = max(max_load, max_temperature)
        minimum_height  = min( instance._viewport.height for instance in instances )
        minimum_width   = min( instance._viewport.width  for instance in instances )

        for font in fonts:
            if font.height <= minimum_height and font.width * max_value <= minimum_width:
                __class__._common_font = font

                break
        else:
            return

        height = font.height
        width  = font.width * max_value

        for instance in instances:
            x = (instance._viewport.width  - width)       / 2
            y = (instance._viewport.height - font.height) / 2

            x = M.math.floor(x)
            y = M.math.ceil(y)

            instance._inner.set_geometry(height=height, width=width, x=x, y=y)


    @M.abc.abstractmethod
    def _get_preformatted_value(self, /):
        pass


    @M.contextlib.contextmanager
    def locked(self, /):
        # Simplifying to the class lock is tempting, but both are needed when
        # the target requires locking (when it's not a terminal).
        with __class__._class_lock:
            with super().locked():
                yield


    def render(self, /, *, force=False):
        with self.locked():
            font  = __class__._common_font
            force = bool(force)
            inner = self._inner
            value = self._get_preformatted_value()

            if force:
                if font:
                    self._viewport.apply_default_render()

                    length = font.width * len(value.affix)

                    for y in range(font.height):
                        row = reversed(inner.rows[y])

                        for cell in M.itertools.islice(row, length):
                            cell.set_style(dim=True)
                else:
                    self.apply_overflow_render()

            if not font:
                return

            for y in range(font.height):
                line = ( font.glyphs.get(char, font.fallback)[y] for char in value.full )
                line = self._empty.join(line)
                line = reversed(line)
                row  = reversed(inner.rows[y])

                for char, cell in zip(line, row):
                    cell.set_style(fg=value.color.FG_DARK, glyph=char)


    def set_geometry(self, /, *args, **kwargs):
        with self.locked():
            super().set_geometry(*args, **kwargs)
            __class__._calc_common_font()




class CurrentWindow(ValueWindow):
    def _get_preformatted_value(self, /):
        return preformat_temperature(self._snapshot.current)




class LoadWindow(ValueWindow):
    def _get_preformatted_value(self, /):
        return preformat_load(self._snapshot.load)




class MaximumWindow(ValueWindow):
    def _get_preformatted_value(self, /):
        return preformat_temperature(self._snapshot.maximum)


    def render(self, /, *args, force=False, **kwargs):
        with self.locked():
            if BREATHER.expired:
                __class__.render = ValueWindow.render

                super().render(*args, force=True, **kwargs)
            elif __class__._common_font:
                self._viewport.apply_noise_render()
            else:
                self.apply_overflow_render()




class MinimumWindow(ValueWindow):
    def _get_preformatted_value(self, /):
        return preformat_temperature(self._snapshot.minimum)




class SmoothedWindow(ValueWindow):
    def _get_preformatted_value(self, /):
        return preformat_temperature(self._snapshot.smoothed)




if __name__ == '__main__':
    main()




# vim: et fenc=utf-8 nobomb sts=4 sw=4 ts=4
